import { test } from 'node:test';
import assert from 'node:assert/strict';
import install from '../index.ts';
function fixture() {
 const hooks = new Map(), commands = new Map(), shortcuts = new Map(), sent = [], notices = [], statuses = [];
 let editor = 'shortcut message';
 let aborts = 0, idle = false, queued = false;
 const pi = { on: (name, fn) => hooks.set(name, fn), registerCommand: (name, fn) => commands.set(name, fn), registerShortcut: (name, fn) => shortcuts.set(name, fn), sendUserMessage: (...args) => sent.push(args) };
 const ctx = { mode: 'tui', isIdle: () => idle, abort: () => { aborts++; }, hasPendingMessages: () => queued,
  ui: { getEditorText: () => editor, setEditorText: text => { editor = text; }, setStatus: (...x) => statuses.push(x), notify: (...x) => notices.push(x) } };
 install(pi);
 // Pi's TUI clears the editor before dispatching a steering submission.
 const input = (overrides = {}) => { editor = ""; return hooks.get('input')({ text: 'new direction', source: 'interactive', streamingBehavior: 'steer', ...overrides }, ctx); };
 return { hooks, commands, shortcuts, sent, notices, statuses, ctx, input, editor: () => editor, setEditor: text => { editor = text; }, setQueued: v => queued = v, aborts: () => aborts, setIdle: v => idle = v, enable: () => commands.get('interrupt-mode').handler('on', ctx) };
}
test('Ctrl+Enter interrupts without enabling Enter mode', async () => { const f = fixture(); await f.shortcuts.get('ctrl+enter').handler(f.ctx); assert.equal(f.aborts(), 1); assert.equal(f.editor(), ''); assert.equal(f.sent.length, 0); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.sent[0][0], 'shortcut message'); assert.equal(f.input().action, 'continue'); });
test('Ctrl+Enter submits immediately when idle', async () => { const f = fixture(); f.setIdle(true); await f.shortcuts.get('ctrl+enter').handler(f.ctx); assert.equal(f.aborts(), 0); assert.deepEqual(f.sent, [['shortcut message']]); assert.equal(f.editor(), ''); });
test('Ctrl+Enter leaves empty input and commands alone', async () => { const f = fixture(); for (const text of ['', '  ', '/model', '!ls', '!!ls']) { f.setEditor(text); await f.shortcuts.get('ctrl+enter').handler(f.ctx); assert.equal(f.editor(), text); } assert.equal(f.aborts(), 0); assert.equal(f.sent.length, 0); });
test('Ctrl+Enter with nothing queued and no draft does not abort', async () => { const f = fixture(); f.setEditor(''); await f.shortcuts.get('ctrl+enter').handler(f.ctx); assert.equal(f.aborts(), 0); assert.equal(f.sent.length, 0); assert.equal(f.editor(), ''); });
test('Ctrl+Enter aborts for a queued-only send when the editor is empty', async () => { const f = fixture(); f.setEditor(''); f.setQueued(true); await f.shortcuts.get('ctrl+enter').handler(f.ctx); assert.equal(f.aborts(), 1); assert.equal(f.editor(), ''); assert.equal(f.sent.length, 0); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.sent.length, 0); });
test('restore recovers submitted text without overwriting a new draft', async () => { const f = fixture(); f.setIdle(true); await f.shortcuts.get('ctrl+enter').handler(f.ctx); await f.commands.get('interrupt-restore').handler('', f.ctx); assert.equal(f.editor(), 'shortcut message'); f.setEditor('new draft'); await f.commands.get('interrupt-restore').handler('', f.ctx); assert.equal(f.editor(), 'new draft'); });
test('restore does not duplicate a message still awaiting cancellation', async () => { const f = fixture(); await f.shortcuts.get('ctrl+enter').handler(f.ctx); await f.commands.get('interrupt-restore').handler('', f.ctx); assert.equal(f.editor(), ''); assert.equal(f.sent.length, 0); f.hooks.get('agent_settled')({}, f.ctx); await f.commands.get('interrupt-restore').handler('', f.ctx); assert.equal(f.editor(), 'shortcut message'); });
test('default off preserves steering', () => { const f = fixture(); assert.equal(f.input().action, 'continue'); assert.equal(f.aborts(), 0); });
test('interrupt waits for settled before sending exactly once', async () => { const f = fixture(); await f.enable(); assert.equal(f.input().action, 'handled'); assert.equal(f.aborts(), 1); assert.equal(f.sent.length, 0); f.setIdle(true); f.hooks.get('agent_settled')({}, f.ctx); assert.deepEqual(f.sent, [['new direction', { deliverAs: 'steer' }]]); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.sent.length, 1); });
test('follow-up, extension, RPC, idle, image and command input bypass interception', async () => { const f = fixture(); await f.enable(); for (const event of [{ streamingBehavior: 'followUp' }, { source: 'extension' }, { source: 'rpc' }, { streamingBehavior: undefined }, { images: [{}] }, { text: '/model' }, { text: '  /skill:hello' }, { text: '   ' }]) assert.equal(f.input(event).action, 'continue'); f.setIdle(true); assert.equal(f.input().action, 'continue'); assert.equal(f.aborts(), 0); });
test('non-TUI mode never interrupts', async () => { const f = fixture(); await f.enable(); f.ctx.mode = 'rpc'; assert.equal(f.input().action, 'continue'); assert.equal(f.aborts(), 0); });
test('rapid messages preserved in order and abort requested once', async () => { const f = fixture(); await f.enable(); f.input({ text: 'first' }); f.input({ text: 'second' }); assert.equal(f.aborts(), 1); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.sent[0][0], 'first\n\nsecond'); });
test('turning off does not discard already captured message', async () => { const f = fixture(); await f.enable(); f.input(); await f.commands.get('interrupt-mode').handler('off', f.ctx); assert.equal(f.input().action, 'continue'); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.sent.length, 1); });
test('status and invalid arguments do not turn mode on', async () => { const f = fixture(); for (const arg of ['', 'status', 'oops']) await f.commands.get('interrupt-mode').handler(arg, f.ctx); assert.equal(f.input().action, 'continue'); });
test('session navigation blocked only while captured input is pending', async () => { const f = fixture(); await f.enable(); for (const name of ['session_before_switch', 'session_before_fork', 'session_before_tree']) assert.equal(f.hooks.get(name)({}, f.ctx), undefined); f.input(); for (const name of ['session_before_switch', 'session_before_fork', 'session_before_tree']) assert.deepEqual(f.hooks.get(name)({}, f.ctx), { cancel: true }); f.hooks.get('agent_settled')({}, f.ctx); assert.equal(f.hooks.get('session_before_switch')({}, f.ctx), undefined); });
